[package]
name = "onet-asset-hub-westend-next"
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
onet-errors = { path = "../../errors" }
onet-records = { path = "../../records" }

subxt = { workspace = true }
