[package]
name = "onet-people-paseo"
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
onet-errors = { path = "../../errors" }
onet-core = { path = "../../core" }
onet-records = { path = "../../records" }

async-recursion = { workspace = true }
log = { workspace = true }
subxt = { workspace = true }
