[package]
name = "onet-api"
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
onet-config = { path = "../config" }
onet-records = { path = "../records" }
onet-pools = { path = "../pools" }
onet-cache = { path = "../cache" }
onet-mcda = { path = "../mcda" }
onet-dn = { path = "../dn" }

actix = { workspace = true }
actix-web = { workspace = true }
actix-web-actors = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
subxt = { workspace = true }
rand = { workspace = true }
redis = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
derive_more = { workspace = true }
