[package]
name = "onet-core"
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]

onet-cache = { path = "../cache" }
onet-chains = { path = "../chains" }
onet-config = { path = "../config" }
onet-errors = { path = "../errors" }
onet-matrix = { path = "../matrix" }
onet-records = { path = "../records" }
onet-report = { path = "../report" }

log = { workspace = true }
redis = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
subxt = { workspace = true }
subxt-signer = { workspace = true }
sp-core = { workspace = true }
